apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketnode-deployment
spec:
  selector:
    matchLabels:
      app: marketnode
  replicas: 1
  template:
    metadata:
      labels:
        app: marketnode
    spec:
      containers:
      - name: marketnode
        image: seki5405/csci5253-project-marketnode:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER
          value: "sw-kafka.kafka-ns.svc.cluster.local:9092"
