apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: server-deployment
    spec:
      containers:
      - name: server
        image: nishantb21/rest:latest
        ports:
        - containerPort: 3001
