apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  type: NodePort
  selector:
    app: server-deployment
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001